# -*- coding: utf-8 -*-
"""u.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OvL2HBes2XO1RlLArP-jn_r4U7Df6Doq
"""

pip install mrjob

from mrjob.job import MRJob

class MRWordFrequencyCount(MRJob):

    def mapper(self, _, line):
        yield "chars", len(line)
        yield "words", len(line.split())
        yield "lines", 1

    def reducer(self, key, values):
        yield key, sum(values)

import pandas as pd
data=pd.read_csv("text file.txt",delimiter='#')
print(data)